---
title: "Data all_cities and univariate distribution of variables"
output: html_document
editor_options: 
  chunk_output_type: console
---

<!-- Run this 'development' chunk -->
<!-- Store every call to library() that you need to explore your functions -->

```{r development, include=FALSE}
library(testthat)
```

<!--
 You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.

If it is the first time you use {fusen}, after 'description', you can directly run the last chunk of the present file with inflate() inside.
--> 

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```


```{r development-dataset}
# Run all this chunk in the console directly
# There already is a dataset in the "inst/" directory
# Make the dataset file available to the current Rmd during development
pkgload::load_all(path = here::here(), export_all = FALSE)

data(all_cities)
```

# all_cities

```{r function-all_cities}
#' all_cities
#' @format A data frame with 1 row per city
#' \describe{
#'   \item{ID}{combination of GHS_FID & city_code (source: UN2018 DB)}
#'   \item{Latitude, Longitude}{geographic coordinates (degrees) (source: UN2018 DB)}
#'   \item{X2018}{number of inhabitants (thousands) in 2018 (source: UN2018 DB)}
#'   \item{X1980}{number of inhabitants (thousands) in 1980 (source: UN2018 DB)}
#'   \item{pop_growth}{population growth between 1980 and 2018 (source: UN2018 DB)}
#'   \item{pop_growth_rate}{annual pop growth (source: UN2018 DB)}
#'   \item{urban_cluster}{to check if more than one agglomeration are in one GHS urban center; it can be 1 (no cluster) or more (source: combination UN2018 and GHS-SMOD class 30)}
#'   \item{multiGHS}{the GHS layer with urban centers is segmented into many polygons; it can be 1 (1 polygon) or more (segmented into many polygons) (source: combination UN2018 and GHS-SMOD class 30)}
#'   \item{Country.Co}{country code (source: UN2018 DB)}
#'   \item{Country.or}{country name (source: UN2018 DB)}
#'   \item{City.Code}{city ID (source: UN2018 DB)}
#'   \item{Urban.Aggl}{city name (source: UN2018 DB)}
#'   \item{Continent}{AS, Asia; AF, Africa; EU, Europe; NA, North America (including central); OC, Oceania; SA, South America (source: custom)}
#'   \item{pop_mean}{mean population over the GHS layer (layer GHS-POP2023) (source: Schiavina et al. 2023. https://ghsl.jrc.ec.europa.eu/ghs_pop2023.php)}
#'   \item{pop_sum}{total population over the GHS layer (layer GHS-POP2023) (source: Schiavina et al. 2023. https://ghsl.jrc.ec.europa.eu/ghs_pop2023.php)}
#'   \item{Area}{area of the urban center (layer GHS-SMOD) (source: JRC 2019)}
#'   \item{plain_area}{surface area of the floodplain (GFPLAIN) within the GHS layer (source: combination of JRC 2019 and Nardi et al., 2019)}
#'   \item{plain_perc}{percentage area occupied by the floodplain within the GHS Layer (source: combination of JRC 2019 and Nardi et al., 2019)}
#'   \item{disc}{Hydrology, Natural Discharge (sub-absin annual average) (source: WaterGAP v2.2, Döll et al. 2003 - extracted from BasinATLAS level 06)}
#'   \item{alti}{Physiography, Elevation (sub-basin average) (source: EarthEnv-DEM90, Robinson et al. 2014 - extracted from BasinATLAS level 06)}
#'   \item{clim}{Climate, Climate Zones (smj}{sub-basin spatial majority) (source: GEnS, Metzger et al. 2013 - extracted from BasinATLAS level 06)}
#'   \item{prec}{Climate, Precipitation (syr}{sub-basin annual average) (source: WorldClim v1.4, Hijmans et al. 2005 - extracted from BasinATLAS level 06)}
#'   \item{clco}{Landcover, Land Cover Classes (smj}{sub-basin spatial majority) (source: GLC2000, Bartholomé & Belward 2005 - extracted from BasinATLAS level 06)}
#'   \item{biom}{Landcover, Terrestrial Biomes (smj}{sub-basin spatial majority) (source: TEOW, Dinerstein et al. 2017 - extracted from BasinATLAS level 06)}
#'   \item{popd}{Anthropogenic, Population Density (sav}{sub-basin average) (source: GPW v4, CIESIN 2016 - extracted from BasinATLAS level 06)}
#'   \item{hdev}{Anthropogenic, Human Development Index (sav}{sub-basin average) (source: HDI v2, Kummu et al. 2018 - extracted from BasinATLAS level 06)}
#'   \item{pop_den}{ population density (pop_sum/Area) (source: custom - from GHS-POP layer)}
#' }
#' @source see source for each variable
"all_cities"
```


# plot_distrib
    
```{r function-plot_distrib}
#' Plot the distribution of a variable in dataset
#' @param dataset a dataset, defaults to all_cities
#' @param varname a variable name
#' @param byclass whether to plot distributions according to class or not. Defaults to FALSE
#' 
#' @return a plot showing the distribution 
#' 
#' @export
plot_distrib <- function(dataset=all_cities,varname, byclass=FALSE){
 vars=sep_data(dataset)
 dataset=dataset %>% 
   dplyr::mutate(xdistrib=.[[varname]])
 datacol=form_palette(dataset,varname)
 plot=ggplot2::ggplot(dataset,
                      ggplot2::aes(x=xdistrib))+
     ggplot2::xlab(varname)+
     ggplot2::theme(legend.position="none")
  if(byclass){
   plot=plot +
    ggplot2::facet_grid(rows=ggplot2::vars(cluster))
 } 
 if(varname %in% sep_data(dataset)$vars_num){
   plot=plot +
    ggplot2::geom_density(lwd=1)+
    ggplot2::geom_rect(data=datacol,
                       ggplot2::aes(x=NULL,y=NULL,
                                    xmin=catmin,
                                    xmax=catmax,
                                    ymin=-Inf,ymax=+Inf,
                                    fill=categories),alpha=0.25)+
    ggplot2::scale_fill_manual(values=datacol$colors)+
    ggplot2::theme(legend.position="none")+
    ggplot2::scale_x_log10()
 }
 if(varname %in% sep_data(dataset)$vars_cat){
   plot=plot+
    ggplot2::geom_bar(stat="count", ggplot2::aes(fill=xdistrib))+
    ggplot2::scale_fill_manual(values=datacol$colors)
 }

 return(plot)
}
```
  
```{r example-plot_distrib}
plot_distrib(all_cities,"clim")
all_cities_clust=run_hclust(all_cities)
plot_distrib(all_cities_clust,"X2018")
plot_distrib(all_cities_clust,"X2018",byclass=TRUE)
```
  
```{r tests-plot_distrib}
test_that("plot_distrib works", {
  expect_true(inherits(plot_distrib, "function")) 
})
```

# describe_city

```{r function-describe_city}
#' Describe all characteristics of a city
#' @param dataset a dataset, defaults to all_cities
#' @param city city name
#' @return a plot
#' @export
describe_city <- function(dataset=all_cities,city){
  dataset_num = dataset %>%
      norm_data() %>% 
      tibble::rownames_to_column("name") %>%
      tidyr::pivot_longer(cols=-name, names_to="varname") %>% 
      dplyr::group_by(varname) %>% 
      dplyr::mutate(maxval=max(value)) %>%
      dplyr::mutate(value=value/maxval) %>% 
      dplyr::ungroup() %>% 
      dplyr::filter(name==city) %>% 
      dplyr::mutate(type="num",
                    index=1:dplyr::n(),
                    text=varname,
                    color="#e9e9e9") %>% 
      dplyr::mutate(x1=0,x2=1,y1=index-0.5,y2=index+1) %>% 
      dplyr::select(type,index,name,varname,value,x1,x2,y1,y2,color,text)
    sepdata=sep_data(dataset)
    dataset_cat=dataset[,c("name",sepdata$vars_cat)]  %>% 
      dplyr::filter(name==city) %>% 
      tidyr::pivot_longer(cols=-name, names_to="varname") %>% 
      dplyr::mutate(color=purrr::map2_chr(varname,value,glourbi:::get_color, dataset=dataset))
    set_colors=c(dataset_cat$color,"#e9e9e9")
    names(set_colors)=set_colors
    dataset_cat=dataset_cat %>% 
      dplyr::mutate(type="cat",
                    index=0:-(dplyr::n()-1)-0.5,
                    text=paste0(varname,": ", value),
                    value=NA,
                    x1=0,
                    x2=1,
                    y1=index,
                    y2=index+1) %>%
      dplyr::select(type,index,name,varname,value,
                    x1,x2,y1,y2,color,text)
  dataset_title=tibble::tibble(type="title",index=max(dataset_num$index)+1,
                               name=city,varname=city,value=NA,
                               x1=0,x2=1,y1=index,y2=index+1,color=NA,text=city)          
 
  dataset_vars=dplyr::bind_rows(dataset_cat,dataset_num,dataset_title)
                                  
  plot=
    ggplot2::ggplot(data=dataset_vars)+
    ggplot2::geom_rect(ggplot2::aes(xmin=x1,ymin=y1,xmax=x2,ymax=y2,fill=color),
                       show.legend=FALSE)+
    ggplot2::geom_segment(ggplot2::aes(x=x1,xend=x2,y=index,yend=index))+
    ggplot2::geom_point(ggplot2::aes(x=value,y=index),size=5, col="blue")+
    ggplot2::geom_text(ggplot2::aes(x=0.5, y=index+0.5,label=text))+
    ggplot2::scale_x_continuous(limits=c(0,1)) +
    ggplot2::scale_fill_manual(values=set_colors)+
    ggplot2::theme_void()
  return(plot)
}
```

```{r example-describe_city}
describe_city(all_cities,"Cordoba--Spain")
all_cities_clust=all_cities %>% run_hclust(15)
describe_city(all_cities_clust,"Cordoba--Spain")
```

```{r tests-describe_city}
test_that("describe_city works", {
  expect_true(inherits(describe_city, "function")) 
})
```


