---
title: "flat_full.Rmd for working package"
output: html_document
editor_options: 
  chunk_output_type: console
---

<!-- Run this 'development' chunk -->
<!-- Store every call to library() that you need to explore your functions -->

```{r development, include=FALSE}
library(testthat)
```

<!--
 You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.

If it is the first time you use {fusen}, after 'description', you can directly run the last chunk of the present file with inflate() inside.
--> 

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```


# sep_data
    
```{r function-sep_data}
#' A function that separates variables in the dataset into 3 groups: identifying (vars_id), descriptive (vars_des), numeric (vars_num)
#' @param dataset a dataset with varnames comparable to all_cities
#' @return a list with elements vars_id, vars_des, vars_cat, vars_num
#' 
#' @export
sep_data <- function(dataset){
  dataset =dataset %>% 
    na.omit()
  # Keep only variables used for calculations of PCA
  vars_id="name"
  vars_des=c("Urban.Aggl","ID","Latitude","Longitude",
             "Continent","Country.Co","City.Code","selectA"
             )
  vars_cat=c("clco","biom","clim")
  if("cluster" %in% colnames(dataset)){vars_cat=c(vars_cat,"cluster")}
  vars_num=c("X2018","X1980","pop_growth","pop_mean","Area","plain_area","plain_perc",
             "disc","alti","prec","hdev")
  return(list(dataset=dataset,
              vars_id=vars_id,
              vars_des=vars_des,
              vars_cat=vars_cat,
              vars_num=vars_num))
}
```
  
```{r example-sep_data}
sep_data(all_cities)
```
  
```{r tests-sep_data}
data(all_cities)
test_that("sep_data works", {
  expect_true(inherits(sep_data, "function")) 
  expect_true(is.list(sep_data(all_cities)))
})
```


# norm_data: a function to normalize data prior to PCA or Hierarchical clustering calculations

```{r function-norm_data}
#' Normalize columns of a dataset (in case they are numeric)
#' @param dataset a dataset
#' @param label the name of the variable used to label individuals. Defaults to "name"
#' @param type the type of normalization. Can be either "center_and_scale" or "rank". Defaults to "rank"
#' @return a normalized dataset in which all numeric variables have been centered and scaled
#' @export
norm_data <- function(dataset, label="name", type="rank"){
  # Keep only complete rows
  datacomp=dataset %>% 
    sep_data() %>% 
    .$dataset
  vars_num=dataset %>% 
    sep_data() %>% 
    .$vars_num
  
  dataset_norm=datacomp[,vars_num] %>% 
    dplyr::select_if(is.numeric)
  if(type=="rank"){
    dataset_norm=dataset_norm %>% 
      dplyr::mutate_all(~rank(.)) 
  }
  if(type=="center_and_scale"){
    dataset_norm=dataset_norm %>% 
      dplyr::mutate_all(~.-mean(.)) %>%
      dplyr::mutate_all(~./sd(.)) 
  }
  dataset_norm=dataset_norm %>% 
    dplyr::mutate(name=datacomp[[label]]) %>% 
    tibble::column_to_rownames({{label}})
  
  return(dataset_norm)
}
```
  
```{r example-norm_data}
norm_data(all_cities)
```
  
```{r tests-norm_data}
test_that("norm_data works", {
  expect_true(inherits(norm_data, "function")) 
})
```

# run_pca
    
```{r function-run_pca}
#' Runs a PCA on dataset
#' @return a PCA object
#' 
#' @export
run_pca <- function(dataset, quali.sup=NULL){
  datacomp=dataset %>% 
    sep_data() %>% 
    .$dataset
  dataset_num = dataset %>%
    glourbi:::norm_data() 
    
  if(!is.null(quali.sup)){
    if(quali.sup %in% sep_data(dataset)$vars_cat){
        quali.sup.value=datacomp[[quali.sup]]
    }
    if(quali.sup %in% sep_data(dataset)$vars_num){
        quali.sup.value=categorize(dataset,quali.sup)
    }
    dataset_num=dataset_num %>% 
          dplyr::mutate({{quali.sup}}:=as.factor(quali.sup.value))
    num_quali.sup=which(colnames(dataset_num)==quali.sup)
  }else{num_quali.sup=NULL}
    
  pca=FactoMineR::PCA(dataset_num,
                      quali.sup=num_quali.sup,
                      graph=FALSE)
  # Additional info regarding quali.sup (quali.sup might be NULL)
  pca$quali.sup.name=quali.sup
  if(!is.null(quali.sup)){
    pca$quali.sup.value=quali.sup.value
  }
  return(pca)
}
```
  
```{r example-run_pca}
data(all_cities)
mypca=run_pca(all_cities)
all_cities_clust=run_hclust(all_cities)
mypca=run_pca(all_cities_clust, quali.sup="cluster")
mypca=run_pca(all_cities_clust,quali.sup="X2018")
```
  
```{r tests-run_pca}
test_that("run_pca works", {
  expect_true(inherits(run_pca, "function")) 
})
```

# rescale
    
```{r function-rescale}
#' Rescale numerical values so that they are centered around 0 and fall between -maxval and maxval
#' @param x a numerical vector
#' @param maxval a scalar such that returned vector falls between -maxval and + maxval
#' @return a scaled vector 
#' 
#' @export
rescale=function(x,maxval=1){
      maxval_effective=max(abs(x), na.rm=TRUE)
      ratio=maxval_effective/maxval
      x=x/ratio
      return(x)
    }
```
  
```{r example-rescale}
rescale(rnorm(100,5,3),maxval=10)
```
  
```{r tests-rescale}
test_that("rescale works", {
  expect_true(inherits(rescale, "function")) 
})
```


# run_hclust
    
```{r function-run_hclust}
#' Runs a hierarchical clustering on dataset
#' @param dataset dataset name
#' @param nclust number of clusters
#' 
#' @return a dataset in which a new variable exists documenting classes (nclust clusters)
#' 
#' @export
run_hclust <- function(dataset, nclust=5,namevar="cluster"){
    # add leading zeros to cluster number to keep order
    ndigits=ceiling(nclust/10)
    # normalize numerical data
    datan=glourbi:::norm_data(dataset)
    distobj=dist(datan)
    tree=hclust(distobj)
    datan=dataset %>% 
      dplyr::mutate(cluster=cutree(tree,k=nclust)) %>% 
      dplyr::mutate(cluster=paste0("cl",
                                   sprintf(glue::glue("%0{ndigits}d"),
                                           cluster)))%>% 
      dplyr::mutate(cluster=as.factor(cluster)) %>% 
      dplyr::select(name,cluster,dplyr::everything())
    return(datan)
}
```
  
```{r example-run_hclust}
data(all_cities)
all_cities_clust=run_hclust(all_cities)
```
  
```{r tests-run_hclust}
test_that("run_hclust works", {
    expect_true(inherits(run_hclust, "function")) 
    all_cities_clust=run_hclust(all_cities)
    expect_s3_class(all_cities_clust,"tbl_df")
  
})
```
  
# plot_pca
    
```{r function-plot_pca}
#' Plot the variables on factorial plan (i,j)
#' @param dataset a dataset on which PCA has been run
#' @param pca a PCA object, as returned by run_pca
#' @param type which type of element you wish to plot ("var" or "ind")
#' @param i factorial axis represented as x (defaults to "Dim.1")
#' @param j factorial axis represented as y (defaults to "Dim.2")
#' @return a PCA plot of individuals or variables
#' @export
plot_pca <- function(dataset,pca, type="var", i="Dim.1", j="Dim.2"){
  # Calculate dataset of coordinates on factorial plan
  pcadata=pca[[type]]$coord %>%
    as.data.frame() %>% 
    tibble::rownames_to_column("name")%>% 
    tibble::as_tibble() 
  pcadata[[i]]=rescale(pcadata[[i]],1)
  pcadata[[j]]=rescale(pcadata[[j]],1)

  # Initialize plot
  plot=ggplot2::ggplot(data=pcadata,
                       ggplot2::aes(.data[[i]],y=.data[[j]]))+
    ggplot2::scale_x_continuous(limits=c(-1.2,1.2))+
    ggplot2::scale_y_continuous(limits=c(-1.2,1.2))+
    ggplot2::theme(legend.position="none")+
    ggplot2::geom_vline(xintercept=0, col="dark grey")+
    ggplot2::geom_hline(yintercept=0, col="dark grey")
    # Calculate color palette if needed
  if("quali.sup" %in% names(pca)){
    datacol=form_palette(dataset=dataset,varname=pca$quali.sup.name)
    plot=plot+
      ggplot2::scale_fill_manual(values=datacol$colors)+
      ggplot2::scale_color_manual(values=c("FALSE"="light grey","TRUE"="black"))
  }
  ### Type var
  if(type=="var"){
    plot=plot+
      ggplot2::geom_segment(ggplot2::aes(x=0,y=0, xend=.data[[i]],yend=.data[[j]]),
                            arrow = ggplot2::arrow(length = ggplot2::unit(0.1,"cm")),
                            col="grey")+
      ggplot2::geom_text(ggplot2::aes(x=1.1*.data[[i]], y=1.1*.data[[j]], label=name))

  }
  # Type ind
  if(type=="ind"){
    if(!is.null(pca$quali.sup.name)){
        pcadata=pcadata %>% 
          dplyr::mutate(group=pca$quali.sup.value,
                        selectA=as.character(dataset$selectA))
        plot=plot +
          ggplot2::geom_point(data=pcadata,
                              shape=21,size=4, alpha=0.5,
                              ggplot2::aes(x=.data[[i]],y=.data[[j]],
                                          fill=group,text=name, color=selectA))
    }else{
        plot=plot + 
          ggplot2::geom_text(ggplot2::aes(x=.data[[i]], y=.data[[j]],
                                          text=name))
    }
  } # end type ind
  plotly=plotly::ggplotly(plot, tooltip="text")
  return(plotly)
}
```
  
```{r example-plot_pca}
data(all_cities)
mypca=run_pca(all_cities,quali.sup="clco")
plot_pca(all_cities,mypca, type="var")
plot_pca(all_cities,mypca, type="ind")

all_cities_clust=run_hclust(all_cities, nclust=10)
mypca=run_pca(all_cities_clust,quali.sup="cluster")
plot_pca(all_cities_clust,mypca,type="var")
plot_pca(all_cities_clust,mypca,type="ind")
```
  
```{r tests-plot_pca}
test_that("plot_pca works", {
  expect_true(inherits(plot_pca, "function")) 
})
```



