---
title: "flat_global_map.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# form_palette
    
```{r function-form_palette}
#' Form a color palette function for a categorical variable
#' @param varname a string corresponding to one of the variables in all_cities.
#' @return a palette function
#' 
#' @noRd
form_palette=function(varname){
  vars=sep_data(all_cities)
  x=all_cities[[varname]]
  if(varname %in% vars$vars_des){
     pal=function(x){
       nb.cols = length(levels(x))
       # get a list of colors according to the total number of factor levels
       colslist = grDevices::colorRampPalette(RColorBrewer::brewer.pal(8, "Set2"))(nb.cols)
       # assign color to each element of x
       cols=colslist[as.numeric(x)]
       return(cols)
     }
  }
  if(varname %in% vars$vars_num){
    pal=function(x){
       nb.cols = 10
       # get a list of colors according to the total number of factor levels
       colslist = grDevices::colorRampPalette(RColorBrewer::brewer.pal(8,"PuBuGn"))(nb.cols)
       # assign color to each element of x
       cutx=cut(x,quantile(x,seq(0,1,by=0.1)),include.lowest=TRUE)
       cols=colslist[as.numeric(cutx)]
       return(cols)
     }
  }
  return(pal)
}

```
  
```{r example-form_palette}
pal=glourbi:::form_palette("X2018")
pal(all_cities$X2018)

pal=glourbi:::form_palette("clim")
pal(all_cities$clim)
```
  
```{r tests-form_palette}
test_that("form_palette works", {
  expect_true(inherits(form_palette, "function")) 
  result_quanti=glourbi:::form_palette("X2018")
  expect_true(inherits(result_quanti,"function"))
  result_quali=glourbi:::form_palette("clim")
  expect_true(inherits(result_quali,"function"))
})
```
  
# plot_palette
    
```{r function-plot_palette}
#' Plots the legend showing values for a color palette
#' @param varname a string corresponding to one of the variables in all_cities.
#' @return a plot
#' 
#' @export
plot_palette=function(varname){
  pal=glourbi:::form_palette(varname)
  vars=glourbi:::sep_data(all_cities)
  x=all_cities[[varname]]
  if(varname %in% vars$vars_des){
    datacol=tibble::tibble(categories= all_cities[[varname]]) %>% 
      unique() %>% 
      dplyr::mutate(colors=pal(categories))
  }
  if(varname %in% vars$vars_num){
    q=quantile(x,seq(0,1,by=0.1))
    datacol=tibble::tibble(x,
                           categories=cut(x,q,include.lowest=T)) %>% 
      dplyr::mutate(colors=pal(x)) %>% 
      dplyr::group_by(categories) %>% 
      dplyr::summarise(colors=unique(colors))
  }

  ggplot2::ggplot(datacol,
                  ggplot2::aes(x=categories, y=1,fill=categories))+
    ggplot2::geom_bar(stat="identity")+
    ggplot2::geom_text(ggplot2::aes(x=1:length(categories),
                                    y=0.5,
                                    label=categories))+
    ggplot2::scale_fill_manual(values=datacol$colors)+
    ggplot2::coord_flip()+
    ggplot2::ggtitle(varname)+
    ggplot2::theme(legend.position="none",
                   axis.title.x = ggplot2::element_blank(),
                   axis.text.x = ggplot2::element_blank(),
                   axis.ticks.x = ggplot2::element_blank(),
                   axis.title.y = ggplot2::element_blank(),
                   axis.text.y = ggplot2::element_blank(),
                   axis.ticks.y = ggplot2::element_blank()
                )

  }
```
  
```{r example-plot_palette}
data(all_cities)
plot_palette("clim")
plot_palette("X2018")
```
  
```{r tests-plot_palette}
test_that("plot_palette works", {
  expect_true(inherits(plot_palette, "function")) 
})
```
    


# global_map

```{r function-global_map}
#' global_map Title

#' @param dataset a dataset, defaults to all_cities
#' @param varname a string corresponding to one of the variables in all_cities. Defaults to X2018
#' @return a leaflet map
#' @export
#'
#' @examples
global_map <- function(dataset=all_cities,varname="X2018") {
  vars=sep_data(dataset)
  pal=form_palette(varname)
  datamap=dataset %>% 
    dplyr::mutate(colors=pal(dataset[[varname]]))
  map= leaflet::leaflet(datamap) %>% 
       leaflet::addTiles() %>% 
       leaflet::addCircleMarkers(col=~colors)
  return(map)
}
```

```{r examples-global_map}
global_map(all_cities,"X2018")
```

```{r tests-global_map}
test_that("global_map works", {

})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_global_map.Rmd", vignette_name = "Go further")
```

