# WARNING - Generated by {fusen} from dev/2-flat_stat.Rmd: do not edit by hand

data(all_cities)
test_that("sep_vars works", {
  expect_true(inherits(sep_vars, "function")) 
  expect_true(is.list(sep_vars(all_cities)))
})
