# WARNING - Generated by {fusen} from dev/3-flat_global_map.Rmd: do not edit by hand

test_that("form_palette works", {
  expect_true(inherits(form_palette, "function")) 
  result_quanti=glourbi:::form_palette(all_cities,"X2018")
  result_quali=glourbi:::form_palette(all_cities,"clim")
})
