# WARNING - Generated by {fusen} from dev/flat_global_map.Rmd: do not edit by hand

test_that("form_palette works", {
  expect_true(inherits(form_palette, "function")) 
  result_quanti=glourbi:::form_palette("X2018")
  expect_true(inherits(result_quanti,"function"))
  result_quali=glourbi:::form_palette("clim")
  expect_true(inherits(result_quali,"function"))
})
