# WARNING - Generated by {fusen} from dev/2-flat_stat.Rmd: do not edit by hand

data(all_cities)
test_that("sep_data works", {
  expect_true(inherits(sep_data, "function")) 
  expect_true(is.list(sep_data(all_cities)))
})
