# WARNING - Generated by {fusen} from dev/2-flat_stat.Rmd: do not edit by hand

test_that("run_hclust works", {
    expect_true(inherits(run_hclust, "function")) 
    all_cities_clust=run_hclust(all_cities)
    expect_s3_class(all_cities_clust,"tbl_df")
  
})
