# WARNING - Generated by {fusen} from dev/1-flat_distrib.Rmd: do not edit by hand

#' all_cities
#' @format A data frame with 1 row per city
#' \describe{
#'   \item{ID}{combination of GHS_FID & city_code (source: UN2018 DB)}
#'   \item{Latitude, Longitude}{geographic coordinates (degrees) (source: UN2018 DB)}
#'   \item{X2018}{number of inhabitants (thousands) in 2018 (source: UN2018 DB)}
#'   \item{X1980}{number of inhabitants (thousands) in 1980 (source: UN2018 DB)}
#'   \item{pop_growth}{population growth between 1980 and 2018 (source: UN2018 DB)}
#'   \item{pop_growth_rate}{annual pop growth (source: UN2018 DB)}
#'   \item{urban_cluster}{to check if more than one agglomeration are in one GHS urban center; it can be 1 (no cluster) or more (source: combination UN2018 and GHS-SMOD class 30)}
#'   \item{multiGHS}{the GHS layer with urban centers is segmented into many polygons; it can be 1 (1 polygon) or more (segmented into many polygons) (source: combination UN2018 and GHS-SMOD class 30)}
#'   \item{Country.Co}{country code (source: UN2018 DB)}
#'   \item{Country.or}{country name (source: UN2018 DB)}
#'   \item{City.Code}{city ID (source: UN2018 DB)}
#'   \item{Urban.Aggl}{city name (source: UN2018 DB)}
#'   \item{Continent}{AS, Asia; AF, Africa; EU, Europe; NA, North America (including central); OC, Oceania; SA, South America (source: custom)}
#'   \item{pop_mean}{mean population over the GHS layer (layer GHS-POP2023) (source: Schiavina et al. 2023. https://ghsl.jrc.ec.europa.eu/ghs_pop2023.php)}
#'   \item{pop_sum}{total population over the GHS layer (layer GHS-POP2023) (source: Schiavina et al. 2023. https://ghsl.jrc.ec.europa.eu/ghs_pop2023.php)}
#'   \item{Area}{area of the urban center (layer GHS-SMOD) (source: JRC 2019)}
#'   \item{plain_area}{surface area of the floodplain (GFPLAIN) within the GHS layer (source: combination of JRC 2019 and Nardi et al., 2019)}
#'   \item{plain_perc}{percentage area occupied by the floodplain within the GHS Layer (source: combination of JRC 2019 and Nardi et al., 2019)}
#'   \item{disc}{Hydrology, Natural Discharge (sub-absin annual average) (source: WaterGAP v2.2, Döll et al. 2003 - extracted from BasinATLAS level 06)}
#'   \item{alti}{Physiography, Elevation (sub-basin average) (source: EarthEnv-DEM90, Robinson et al. 2014 - extracted from BasinATLAS level 06)}
#'   \item{clim}{Climate, Climate Zones (smj}{sub-basin spatial majority) (source: GEnS, Metzger et al. 2013 - extracted from BasinATLAS level 06)}
#'   \item{prec}{Climate, Precipitation (syr}{sub-basin annual average) (source: WorldClim v1.4, Hijmans et al. 2005 - extracted from BasinATLAS level 06)}
#'   \item{clco}{Landcover, Land Cover Classes (smj}{sub-basin spatial majority) (source: GLC2000, Bartholomé & Belward 2005 - extracted from BasinATLAS level 06)}
#'   \item{biom}{Landcover, Terrestrial Biomes (smj}{sub-basin spatial majority) (source: TEOW, Dinerstein et al. 2017 - extracted from BasinATLAS level 06)}
#'   \item{popd}{Anthropogenic, Population Density (sav}{sub-basin average) (source: GPW v4, CIESIN 2016 - extracted from BasinATLAS level 06)}
#'   \item{hdev}{Anthropogenic, Human Development Index (sav}{sub-basin average) (source: HDI v2, Kummu et al. 2018 - extracted from BasinATLAS level 06)}
#'   \item{pop_den}{ population density (pop_sum/Area) (source: custom - from GHS-POP layer)}
#' }
#' @source see source for each variable
"all_cities"
