# WARNING - Generated by {fusen} from dev/flat_shiny.Rmd: do not edit by hand

#' @import shiny
#' @export
#' @examples
#' app_ui()
app_ui <- function() {
  shiny::navbarPage(
    title =
      shiny::div(
      shiny::  img(
          src = "www/GloUrb.png",
          height = 40,
          width = 100,
          style = "margin:-11px -12px"
        )
      )#,
    #tabPanel("Profils",mod_long_profiles_ui("long_profiles_ui_1")),
    #tabPanel("Modèle régional",mod_regional_models_ui("regional_models_ui_1")),
    #tabPanel("Test dev",mod_test_ui("test_ui_1"))
  )
}
