# WARNING - Generated by {fusen} from dev/3-flat_global_map.Rmd: do not edit by hand

#' Categorize quantitative variable into categories based on deciles
#' @param dataset a dataset, defaults to all_cities
#' @param varname a string corresponding to one of the variables in all_cities.
#' @return a categorized vector
#' 
#' @export
#' @examples
#' categorize(all_cities,"X2018")
categorize <- function(dataset=all_cities, varname){
  if(varname %in% sep_data(dataset)$vars_num){
    x=dataset[[varname]]
    result=cut(x, quantile(x,seq(0,1,by=0.1)),include.lowest=TRUE)
  return(result)
  }
}
