# WARNING - Generated by {fusen} from dev/1-flat_distrib.Rmd: do not edit by hand

#' Describe all characteristics of a city
#' @dataset a dataset, defaults to all_cities
#' @param city city name
#' @return a plot
#' 
#' @export
#' @examples
#' describe_city()
describe_city <- function(dataset=all_cities,city){
  datacomp=dataset %>% 
    sep_data() %>% 
    .$dataset
  dataset_num = dataset %>%
    glourbi:::norm_data() 
}
