# WARNING - Generated by {fusen} from dev/2-flat_stat.Rmd: do not edit by hand

#' Title
#' 
#' Description
#' @param a glourbi dataset with varnames comparable to all_cities, with a cluster descriptor
#' @param display_ranks whether to show raw values of quantitative variables or ranks (as calculated by function norm_data) defaults to FALSE
#' @return a plot gathering boxplots as facets
#' 
#' @export
#' @examples
#' data(all_cities)
#' all_cities_clust=run_hclust(all_cities, nclust=2)
#' describe_clusters(all_cities_clust,display_ranks=TRUE)
#' describe_clusters(all_cities_clust,display_ranks=FALSE)
describe_clusters <- function(dataset,display_ranks=FALSE){
    if (display_ranks){
      dataset_num=norm_data(dataset)
    }else{
      vars_num=dataset %>% 
        sep_vars() %>% 
        .$vars_num
      dataset_num=dataset[,vars_num]
    }
    dataset_boxplots=cbind(cluster=dataset$cluster,dataset_num) %>% 
      tidyr::pivot_longer(cols=-cluster)
    datacol=form_palette(dataset,"cluster") 
    ggplot2::ggplot(dataset_boxplots,
                    ggplot2::aes(x=cluster,y=value, fill=cluster))+
      ggplot2::geom_boxplot()+
      ggplot2::facet_wrap(ggplot2::vars(name), scales="free_y")+
      ggplot2::scale_fill_manual(values=datacol$colors)
}
