# WARNING - Generated by {fusen} from dev/3-flat_global_map.Rmd: do not edit by hand

#' Form a color palette function for a categorical variable
#' @param dataset a dataset, defaults to all_cities
#' @param varname a string corresponding to one of the variables in all_cities.
#' @return a palette function
#' @export
#' @noRd
#' @examples
#' datacol=form_palette(all_cities,"X2018")
#' datacol
#'
#' datacol=form_palette(all_cities,"clim")
#' datacol
form_palette=function(dataset=all_cities,varname){
  vars=sep_data(dataset)
  x=dataset[[varname]]
  
  pal=fun_palette(dataset,varname)
  # For categorical variables
  if(varname %in% vars$vars_cat){
     datacol=tibble::tibble(categories= dataset[[varname]]) %>% 
       unique() %>% 
       dplyr::mutate(colors=pal(categories))
  }
  # For numerical variables
  if(varname %in% vars$vars_num){
    q=quantile(x,seq(0,1,by=0.1))
    datacol=tibble::tibble(x,
                           categories=cut(x,q,include.lowest=T)) %>% 
      dplyr::mutate(colors=pal(x)) %>% 
      dplyr::group_by(categories) %>% 
      dplyr::summarise(colors=unique(colors)) %>% 
      dplyr::arrange(categories) %>% 
      dplyr::mutate(catmin=q[1:10],
                    catmax=q[2:11])
    names(datacol$colors)=datacol$categories
  }
  # For other variables
  if(!(varname %in% c(vars$vars_cat,vars$vars_num))){
    datacol=tibble::tibble(categories= dataset[[varname]]) %>% 
       dplyr::group_by(categories) %>%  
       dplyr::summarise(colors=pal(categories)) %>% 
       dplyr::arrange(categories)
    
  }
  return(datacol)
}

