# WARNING - Generated by {fusen} from dev/flat_global_map.Rmd: do not edit by hand

#' Form a color palette function for a categorical variable
#' @param varname a string corresponding to one of the variables in all_cities.
#' @return a palette function
#' 
#' @noRd
#' @examples
#' pal=glourbi:::form_palette("X2018")
#' pal(all_cities$X2018)
#'
#' pal=glourbi:::form_palette("clim")
#' pal(all_cities$clim)
form_palette=function(varname){
  vars=sep_data(all_cities)
  x=all_cities[[varname]]
  if(varname %in% vars$vars_des){
     pal=function(x){
       nb.cols = length(levels(x))
       # get a list of colors according to the total number of factor levels
       colslist = grDevices::colorRampPalette(RColorBrewer::brewer.pal(8, "Set2"))(nb.cols)
       # assign color to each element of x
       cols=colslist[as.numeric(x)]
       return(cols)
     }
  }
  if(varname %in% vars$vars_num){
    pal=function(x){
       nb.cols = 10
       # get a list of colors according to the total number of factor levels
       colslist = grDevices::colorRampPalette(RColorBrewer::brewer.pal(8,"PuBuGn"))(nb.cols)
       # assign color to each element of x
       cutx=cut(x,quantile(x,seq(0,1,by=0.1)),include.lowest=TRUE)
       cols=colslist[as.numeric(cutx)]
       return(cols)
     }
  }
  return(pal)
}

