# WARNING - Generated by {fusen} from dev/3-flat_global_map.Rmd: do not edit by hand

#' Build a palette function
#' @param dataset a dataset, defaults to all_cities
#' @param varname a string corresponding to one of the variables in all_cities.
#' @return a function
#' 
#' @export
#' @examples
#' fun_palette(all_cities,"clim")
fun_palette <- function(dataset=all_cities,varname){
  vars=sep_data(dataset)
  x=dataset[[varname]]
  # For categorical variables
  if(varname %in% vars$vars_cat){
     pal=function(x){
       nb.cols = length(levels(x))
       # get a list of colors according to the total number of factor levels
       colslist = grDevices::colorRampPalette(RColorBrewer::brewer.pal(8, "Set2"))(nb.cols)
       # assign color to each element of x
       cols=colslist[as.numeric(x)]
       return(cols)
     }
  }
  # For numerical variables
  if(varname %in% vars$vars_num){
        pal=function(x){
             # get a list of colors according to the total number of factor levels
             colslist = grDevices::colorRampPalette(RColorBrewer::brewer.pal(8,"PuBuGn"))(10)
             # assign color to each element of x
             cutx=cut(x,quantile(x,seq(0,1,by=0.1)),include.lowest=TRUE)
             cols=colslist[as.numeric(cutx)]
             return(cols)
        }
  }
  # For other variables
  if(!(varname %in% c(vars$vars_cat,vars$vars_num))){
      pal=function(x){return("#FF0000",length(x))}
  }
  return(pal)
}
