# WARNING - Generated by {fusen} from dev/3-flat_global_map.Rmd: do not edit by hand

#' Returns the color associated with a certain value of a categorical variable
#' @param dataset a dataset, defaults to all_cities
#' @param varname name of the variable considered, as string
#' @param value name of the value, as string
#' @return a hex color value
#' 
#' @export
#' @examples
#' get_color(all_cities,"biom","b08")
#' all_cities_clust=run_hclust(all_cities,15)
#' get_color(all_cities_clust,"cluster","cl12")
get_color=function(dataset=all_cities,varname,value){
  result=form_palette(dataset,varname) %>%
    dplyr::filter(as.vector(categories)==value) %>%
    dplyr::pull(colors)
  return(result)
}
