# WARNING - Generated by {fusen} from dev/2-flat_stat.Rmd: do not edit by hand

#' Normalize columns of a dataset (in case they are numeric)
#' @param dataset a dataset
#' @param label the name of the variable used to label individuals. Defaults to "name"
#' @param type the type of normalization. Can be either "center_and_scale" or "rank". Defaults to "rank"
#' @return a normalized dataset in which all numeric variables have been centered and scaled
#' @export
#' @examples
#' norm_data(all_cities)
norm_data <- function(dataset, label="name", type="rank"){
  # Keep only complete rows
  datacomp=dataset %>% 
    sep_vars() %>% 
    .$dataset
  vars_num=dataset %>% 
    sep_vars() %>% 
    .$vars_num
  
  dataset_norm=datacomp[,vars_num] %>% 
    dplyr::select_if(is.numeric)
  if(type=="rank"){
    dataset_norm=dataset_norm %>% 
      dplyr::mutate_all(~rank(.)) 
  }
  if(type=="center_and_scale"){
    dataset_norm=dataset_norm %>% 
      dplyr::mutate_all(~.-mean(.)) %>%
      dplyr::mutate_all(~./sd(.)) 
  }
  dataset_norm=dataset_norm %>% 
    dplyr::mutate(name=datacomp[[label]]) %>% 
    tibble::column_to_rownames({{label}})
  
  return(dataset_norm)
}
