# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' Normalize columns of a dataset (in case they are numeric)
#' @param dataset a dataset
#' @return a normalized dataset in which all numeric variables have been centered and scaled
#' 
#' @noRd
#' @examples
#' glourbi:::norm_data(all_cities)
norm_data <- function(dataset, label="name"){
  # Keep only complete rows
  datacomp=dataset %>% 
    sep_data() %>% 
    .$dataset
  vars_num=dataset %>% 
    sep_data() %>% 
    .$vars_num
  
  dataset_num=datacomp[,vars_num]
  
  # All numeric variables are centered and scaled
  dataset_norm=dataset_num %>% 
    dplyr::select_if(is.numeric) %>% 
    dplyr::mutate_all(~.-mean(.)) %>%
    dplyr::mutate_all(~./sd(.)) %>% 
    dplyr::mutate(name=datacomp[[label]]) %>% 
    tibble::column_to_rownames({{label}})
  return(dataset_norm)
}
