# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' Plot the variables on factorial plan (i,j)
#' @param pca a PCA object, as returned by run_pca
#' @param type which type of element you wish to plot ("var" or "ind")
#' @param i factorial axis represented as x (defaults to "Dim.1")
#' @param j factorial axis represented as y (defaults to "Dim.2")
#' @return
#' @export
#' @examples
#' data(all_cities)
#' mypca=run_pca(all_cities,quali.sup="clco")
#' plot_pca(mypca, type="var")
#' plot_pca(mypca,type="ind")
#'
#' all_cities_clust=run_hclust(all_cities, nclust=15)
#' mypca=run_pca(all_cities_clust,quali.sup="cluster")
#' plot_pca(mypca,type="var")
#' plot_pca(mypca,type="ind")
plot_pca <- function(pca, type="var", i="Dim.1", j="Dim.2"){
  pcadata=pca[[type]]$coord %>%
    as.data.frame() %>% 
    tibble::rownames_to_column("name")%>% 
    tibble::as_tibble() 
  plot=ggplot2::ggplot(data=pcadata,
                       ggplot2::aes(.data[[i]],y=.data[[j]]))
  ### Type var
  if(type=="var"){
     if(!is.null(pca$quali.sup.name)){
          dataquali=pca$quali.sup$coord %>%  
            as.data.frame() %>% 
            dplyr::mutate_all(rescale) %>% 
            tibble::rownames_to_column("group") 
          print(dataquali)
          plot=plot +
            ggplot2::geom_text(data=dataquali,
                               ggplot2::aes(x=.data[[i]],y=.data[[j]],
                                            label=group,col=group))
      }
    plot=plot+
      ggplot2::geom_segment(ggplot2::aes(x=0,y=0, xend=.data[[i]],yend=.data[[j]]),
                            arrow = ggplot2::arrow(length = ggplot2::unit(0.1,"cm")),
                            col="grey")+
      ggplot2::geom_text(ggplot2::aes(x=1.1*.data[[i]], y=1.1*.data[[j]], label=name))

  }
  # Type ind
  if(type=="ind"){
    if(!is.null(pca$quali.sup.name)){
        pcadata=pcadata %>% 
          dplyr::mutate(group=pca$quali.sup.value)
        geom=ggplot2::geom_text(data=pcadata,
                             ggplot2::aes(x=.data[[i]],y=.data[[j]],
                                          label=name,col=group))
    }else{
      geom=ggplot2::geom_text(ggplot2::aes(x=.data[[i]], y=.data[[j]],
                                  label=name))
    }
    plot=plot+geom
  } # end type ind
  plot=plot+
    ggplot2::scale_x_continuous(limits=range(pcadata[[i]]*1.2))+
    ggplot2::scale_y_continuous(limits=range(pcadata[[j]]*1.2))
  
  return(plot)
}
