# WARNING - Generated by {fusen} from dev/1-flat_distrib.Rmd: do not edit by hand

#' Plot the distribution of a variable in dataset
#' @param dataset a dataset, defaults to all_cities
#' @param varname a variable name
#' @param byclass whether to plot distributions according to class or not. Defaults to FALSE
#' 
#' @return a plot showing the distribution 
#' 
#' @export
#' @examples
#' plot_distrib(all_cities,"clim")
#' all_cities_clust=run_hclust(all_cities)
#' plot_distrib(all_cities_clust,"X2018")
#' plot_distrib(all_cities_clust,"X2018",byclass=TRUE)
plot_distrib <- function(dataset=all_cities,varname, byclass=FALSE){
 vars=sep_data(dataset)
 dataset=dataset %>% 
   dplyr::mutate(xdistrib=.[[varname]])
 plot=ggplot2::ggplot(dataset,ggplot2::aes(x=xdistrib))
  if(byclass){
   plot=plot +
    ggplot2::facet_grid(rows=ggplot2::vars(cluster))+
     ggplot2::xlab(varname)
 } 
 if(varname %in% sep_data(dataset)$vars_num){
   datacol=form_palette(dataset,varname)
   plot=plot+
    ggplot2::geom_rect(data=datacol,
                       ggplot2::aes(x=NULL,y=NULL,
                                    xmin=catmin,
                                    xmax=catmax,
                                    ymin=0,ymax=1,
                                    fill=colors))+
    ggplot2::scale_fill_manual(values=datacol$colors)+
    ggplot2::geom_density(data=dataset)+
    ggplot2::theme(legend.position="none")
 }
 if(varname %in% sep_data(dataset)$vars_cat){
   plot=plot+
    ggplot2::geom_bar()
 }

 return(plot)
}
