# WARNING - Generated by {fusen} from dev/3-flat_global_map.Rmd: do not edit by hand

#' Plots the legend showing values for a color palette
#' @param dataset a dataset, defaults to all_cities
#' @param varname a string corresponding to one of the variables in all_cities.
#' @return a plot
#' 
#' @export
#' @examples
#' data(all_cities)
#' plot_palette(all_cities,"clim")
#' plot_palette(all_cities,"X2018")
plot_palette=function(dataset=all_cities,varname){
  datacol=form_palette(dataset,varname) 
  
  ggplot2::ggplot(datacol,
                  ggplot2::aes(x=categories, y=1,fill=categories))+
    ggplot2::geom_bar(stat="identity")+
    ggplot2::geom_text(ggplot2::aes(x=1:length(categories),
                                    y=0.5,
                                    label=categories))+
    ggplot2::scale_fill_manual(values=datacol$colors)+
    ggplot2::coord_flip()+
    ggplot2::xlab(varname)+
    ggplot2::theme_void()+
    ggplot2::theme(legend.position="none")
  }
