# WARNING - Generated by {fusen} from dev/flat_global_map.Rmd: do not edit by hand

#' Plots the legend showing values for a color palette
#' @param varname a string corresponding to one of the variables in all_cities.
#' @return a plot
#' 
#' @export
#' @examples
#' data(all_cities)
#' plot_palette("clim")
#' plot_palette("X2018")
plot_palette=function(varname){
  pal=glourbi:::form_palette(varname)
  vars=glourbi:::sep_data(all_cities)
  x=all_cities[[varname]]
  if(varname %in% vars$vars_des){
    datacol=tibble::tibble(categories= all_cities[[varname]]) %>% 
      unique() %>% 
      dplyr::mutate(colors=pal(categories))
  }
  if(varname %in% vars$vars_num){
    q=quantile(x,seq(0,1,by=0.1))
    datacol=tibble::tibble(x,
                           categories=cut(x,q,include.lowest=T)) %>% 
      dplyr::mutate(colors=pal(x)) %>% 
      dplyr::group_by(categories) %>% 
      dplyr::summarise(colors=unique(colors))
  }

  ggplot2::ggplot(datacol,
                  ggplot2::aes(x=categories, y=1,fill=categories))+
    ggplot2::geom_bar(stat="identity")+
    ggplot2::geom_text(ggplot2::aes(x=1:length(categories),
                                    y=0.5,
                                    label=categories))+
    ggplot2::scale_fill_manual(values=datacol$colors)+
    ggplot2::coord_flip()+
    ggplot2::ggtitle(varname)+
    ggplot2::theme(legend.position="none",
                   axis.title.x = ggplot2::element_blank(),
                   axis.text.x = ggplot2::element_blank(),
                   axis.ticks.x = ggplot2::element_blank(),
                   axis.title.y = ggplot2::element_blank(),
                   axis.text.y = ggplot2::element_blank(),
                   axis.ticks.y = ggplot2::element_blank()
                )

  }
