# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' Rescale numerical values so that they are centered around 0 and fall between -maxval and maxval
#' @return
#' 
#' @export
#' @examples
#' rescale(rnorm(100,5,3),maxval=10)
rescale=function(x,maxval=1){
      x=x-mean(x, na.rm=TRUE)
      maxval_effective=max(abs(x), na.rm=TRUE)
      ratio=maxval_effective/maxval
      x=x/ratio
      return(x)
    }
