# WARNING - Generated by {fusen} from dev/flat_full.Rmd: do not edit by hand

#' Runs a hierarchical clustering on dataset
#' @dataset dataset name
#' @nclust number of clusters
#' 
#' @return
#' 
#' @export
#' @examples
#' data(all_cities)
#' all_cities_clust=run_hclust(all_cities)
run_hclust <- function(dataset, nclust=5,namevar="cluster"){
    # add leading zeros to cluster number to keep order
    ndigits=ceiling(nclust/10)
    # normalize numerical data
    datan=norm_data(dataset)
    distobj=dist(datan)
    tree=hclust(distobj)
    datan=datan %>% 
      tibble::rownames_to_column("name") %>% 
      tibble::as_tibble() %>% 
      dplyr::mutate(cluster=cutree(tree,k=nclust)) %>% 
      dplyr::mutate(cluster=paste0("cl",
                                   sprintf(glue::glue("%0{ndigits}d"),
                                           cluster))) %>% 
      dplyr::select(name,everything())
    return(datan)
}
