# WARNING - Generated by {fusen} from dev/2-flat_stat.Rmd: do not edit by hand

#' Runs a hierarchical clustering on dataset
#' @param dataset a glourbi dataset with varnames comparable to all_cities
#' @param nclust number of clusters
#' 
#' @return a dataset in which a new variable exists documenting classes (nclust clusters)
#' 
#' @export
#' @examples
#' data(all_cities)
#' all_cities_clust=run_hclust(all_cities)
run_hclust <- function(dataset, nclust=5,namevar="cluster"){
    # add leading zeros to cluster number to keep order
    ndigits=ceiling(nclust/10)
    # normalize numerical data
    # datan=glourbi:::norm_data(dataset)
    # distobj=dist(datan)
    vars=sep_vars(dataset)
    dataclust=dataset %>% 
      dplyr::select(vars$vars_cat,vars$vars_num)
    distobj=cluster::daisy(dataclust)
    
    tree=hclust(distobj)
    datan=dataset %>% 
      dplyr::mutate(cluster=cutree(tree,k=nclust)) %>% 
      dplyr::mutate(cluster=paste0("cl",
                                   sprintf(glue::glue("%0{ndigits}d"),
                                           cluster)))%>% 
      dplyr::mutate(cluster=as.factor(cluster)) %>% 
      dplyr::select(name,cluster,dplyr::everything())
    return(datan)
}
