# WARNING - Generated by {fusen} from dev/2-flat_stat.Rmd: do not edit by hand

#' Runs a PCA on dataset
#' @return a PCA object
#' 
#' @export
#' @examples
#' data(all_cities)
#' mypca=run_pca(all_cities)
#' all_cities_clust=run_hclust(all_cities)
#' mypca=run_pca(all_cities_clust, quali.sup="cluster")
run_pca <- function(dataset, quali.sup=NULL){
  datacomp=dataset %>% 
    sep_data() %>% 
    .$dataset
  dataset_num = dataset %>%
    glourbi:::norm_data() 
    
  if(!is.null(quali.sup)){
    dataset_num=dataset_num %>% 
      dplyr::mutate({{quali.sup}}:=as.factor(datacomp[[quali.sup]]))
    num_quali.sup=which(colnames(dataset_num)==quali.sup)
  }else{num_quali.sup=NULL}
    
  pca=FactoMineR::PCA(dataset_num,
                      quali.sup=num_quali.sup)
  pca$quali.sup.name=quali.sup
  if(!is.null(quali.sup)){pca$quali.sup.value=datacomp[[quali.sup]]}
  return(pca)
}
